Traceback (most recent call last):
  File "/home/david/anaconda3/envs/jaxpi/lib/python3.13/site-packages/scipy/io/matlab/_mio.py", line 39, in _open_file
    return open(file_like, mode), True
           ~~~~^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/ks.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/work/repos/deep-learning-pde/jaxpi/examples/cahn_hilliard/main.py", line 41, in <module>
    app.run(main)
    ~~~~~~~^^^^^^
  File "/home/david/anaconda3/envs/jaxpi/lib/python3.13/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
    ~~~~~~~~~^^^^^^^^^^^^
  File "/home/david/anaconda3/envs/jaxpi/lib/python3.13/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ~~~~^^^^^^
  File "/home/david/work/repos/deep-learning-pde/jaxpi/examples/cahn_hilliard/main.py", line 33, in main
    train.train_and_evaluate(FLAGS.config, FLAGS.workdir)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/work/repos/deep-learning-pde/jaxpi/examples/cahn_hilliard/train.py", line 69, in train_and_evaluate
    u_ref, t_star, x_star = get_dataset()
                            ~~~~~~~~~~~^^
  File "/home/david/work/repos/deep-learning-pde/jaxpi/examples/cahn_hilliard/utils.py", line 5, in get_dataset
    data = scipy.io.loadmat("data/ks.mat")
  File "/home/david/anaconda3/envs/jaxpi/lib/python3.13/site-packages/scipy/io/matlab/_mio.py", line 233, in loadmat
    with _open_file_context(file_name, appendmat) as f:
         ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/anaconda3/envs/jaxpi/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/home/david/anaconda3/envs/jaxpi/lib/python3.13/site-packages/scipy/io/matlab/_mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/anaconda3/envs/jaxpi/lib/python3.13/site-packages/scipy/io/matlab/_mio.py", line 45, in _open_file
    return open(file_like, mode), True
           ~~~~^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/ks.mat'
